# Generated by Django 3.0.5 on 2020-04-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200406_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(choices=[('software_engineer', 'Software Engineer'), ('frontend_engineer', 'Front End Engineer'), ('backend_engineer', 'Back End Engineer'), ('graphic_designer', 'Graphic Designer'), ('ux_designer', 'UX Designer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
