# Generated by Django 3.0.5 on 2020-04-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200406_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, choices=[('software_engineer', 'Software Engineer'), ('frontend_engineer', 'Front End Engineer'), ('backend_engineer', 'Back End Engineer'), ('graphic_designer', 'Graphic Designer'), ('ux_designer', 'UX Designer')], max_length=20, null=True),
        ),
    ]
