# Generated by Django 3.0.5 on 2020-04-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200406_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, choices=[('software engineer', 'Software Engineer'), ('frontend engineer', 'Front End Engineer'), ('backend engineer', 'Back End Engineer'), ('graphic designer', 'Graphic Designer'), ('ux designer', 'UX Designer')], max_length=20, null=True),
        ),
    ]
