# Generated by Django 3.0.5 on 2020-04-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_avatar_img_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
