# Generated by Django 3.0.5 on 2020-05-06 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_follows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follows',
        ),
    ]
