# Generated by Django 3.0.5 on 2020-04-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20200408_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
