# Generated by Django 3.0.5 on 2020-05-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resources_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
